name: Download File from GitHub Release

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'owner/repo (مثلا termux/termux-packages)'
        required: true
        default: 'termux/termux-packages'
      tag:
        description: 'اسم تگ یا نسخه (مثلا v1.0.0) یا "latest" برای آخرین نسخه'
        required: true
        default: 'latest'
      pattern:
        description: 'اسم فایل مورد نظر (مثلا *.deb یا اسم کامل فایل)'
        required: true
        default: '*.deb'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Release Asset
        uses: robinraju/release-downloader@v1.11
        with:
          repository: ${{ github.event.inputs.repo }}
          tag: ${{ github.event.inputs.tag }}
          fileName: ${{ github.event.inputs.pattern }}
          out-file-path: 'downloads'
          extract: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-files
          path: downloads/
